// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type { LoginData, LoginResponse2 } from './types.gen'

export class AuthService {
  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @param data.cache Next.js option
   * @returns LoginResponse
   * @throws ApiError
   */
  public static login(data: LoginData): CancelablePromise<LoginResponse2> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/auth/login',
      path: {
        cache: data.cache,
      },
      body: data.requestBody,
      mediaType: 'application/json',
    })
  }
}
