// This file is auto-generated by @hey-api/openapi-ts

export type LoginDto = {
  email: string
  password: string
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export type UserInfo = {
  gender: Gender | null
  id: string
  email: string
  name: string
  firstName: string | null
  lastName: string | null
  verifiedEmail: boolean
  memberType: string
  birthday: string | null
  avatar: string | null
  bio: string | null
  phoneNumber: string | null
  country: string | null
  city: string | null
  district: string | null
  address: string | null
  postalCode: string | null
  status: string
  metadata: {
    [key: string]: unknown
  } | null
}

export type LoginResponse = {
  accessToken: string
  refreshToken: string
  user: UserInfo
}

/**
 * Cache type
 */
export enum CacheType {
  DEFAULT = 'default',
  FORCE_CACHE = 'force-cache',
  NO_CACHE = 'no-cache',
  NO_STORE = 'no-store',
  ONLY_IF_CACHED = 'only-if-cached',
  RELOAD = 'reload',
}

export type NextJsOptions = {
  /**
   * Revalidate time in seconds
   */
  revalidate?: number
  type?: CacheType
  /**
   * Cache tags
   */
  tags?: Array<string>
}

export type LoginData = {
  /**
   * Next.js option
   */
  cache?: NextJsOptions
  requestBody: LoginDto
}

export type LoginResponse2 = LoginResponse
